### ISSUE TITLE
compiling error 'getVector3fMap'

### ISSUE THREAD

**Issue by ri-ceres** [yayaneath/GeoGrasp#1]
When trying to build catkin workspace, build fails with: `error: ‘const class Eigen::Map<Eigen::Matrix<float, 3, 1>, 0, Eigen::Stride<0, 0> >’ has no member named ‘getVector3fMap’`

Full trace:

```
In file included from /home/user/src/geograsp/geograsp/include/geograsp/GeoGrasp.h:14:0,
                 from /home/user/src/geograsp/geograsp/lib/geograsp/GeoGrasp.cpp:1:
/usr/include/pcl-1.8/pcl/common/geometry.h: In instantiation of ‘float pcl::geometry::distance(const PointT&, const PointT&) [with PointT = Eigen::Map<Eigen::Matrix<float, 3, 1>, 0, Eigen::Stride<0, 0> >]’:
/home/user/src/geograsp/geograsp/lib/geograsp/GeoGrasp.cpp:232:44:   required from here
/usr/include/pcl-1.8/pcl/common/geometry.h:62:33: error: ‘const class Eigen::Map<Eigen::Matrix<float, 3, 1>, 0, Eigen::Stride<0, 0> >’ has no member named ‘getVector3fMap’
       Eigen::Vector3f diff = p1.getVector3fMap () - p2.getVector3fMap ();
                              ~~~^~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/common/geometry.h:62:56: error: ‘const class Eigen::Map<Eigen::Matrix<float, 3, 1>, 0, Eigen::Stride<0, 0> >’ has no member named ‘getVector3fMap’
       Eigen::Vector3f diff = p1.getVector3fMap () - p2.getVector3fMap ();
                                                     ~~~^~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/common/geometry.h: In instantiation of ‘float pcl::geometry::distance(const PointT&, const PointT&) [with PointT = Eigen::Matrix<float, 3, 1>]’:
/home/user/src/geograsp/geograsp/lib/geograsp/GeoGrasp.cpp:484:21:   required from here
/usr/include/pcl-1.8/pcl/common/geometry.h:62:33: error: ‘const class Eigen::Matrix<float, 3, 1>’ has no member named ‘getVector3fMap’
       Eigen::Vector3f diff = p1.getVector3fMap () - p2.getVector3fMap ();
                              ~~~^~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/common/geometry.h:62:56: error: ‘const class Eigen::Matrix<float, 3, 1>’ has no member named ‘getVector3fMap’
       Eigen::Vector3f diff = p1.getVector3fMap () - p2.getVector3fMap ();
```

**Comment by yayaneath** [comment]
Hi @ri-ceres 

It seems that the code of the function `pcl::geometry::distance` has changed from the PCL version 1.7 to the 1.8 and above. GeoGrasp was tested on the PCL 1.7, as stated in the [README](https://github.com/yayaneath/GeoGrasp/blob/master/README.md) page. In that version, this function must be called passing the `Vector3fMap` from the points (find more [here](http://docs.pointclouds.org/1.7.2/a01364_source.html#l00060)). From the PCL 1.8, the function itself performs this call inside of it (find more [here](http://docs.pointclouds.org/trunk/common_2include_2pcl_2common_2geometry_8h_source.html#l00060)).

Hence, the quick fix for your PCL version would be changing this line in `GeoGrasp.cpp`:

`
float objWidth = pcl::geometry::distance(this->firstGraspPoint.getVector3fMap(), this->secondGraspPoint.getVector3fMap());
`

For this call:

`
float objWidth = pcl::geometry::distance(this->firstGraspPoint, this->secondGraspPoint);
`

**Comment by ri-ceres** [comment]
That looks like it should resolve the issue. I'll confirm that this is the case when I am able to resume work on my project next week. Thanks!

**Comment by planetceres** [comment]
Following up to say that this issue has been resolved. Thanks!

**Comment by ri-ceres** [comment]
Following up to confirm that this issue has been resolved. Thanks!

**Comment by adelelakour** [comment]
Hi yayaneath,
First of all, thanks for uploading the code :D 

Now, I'm facing the same issue. I've replaced  

float objWidth = pcl::geometry::distance(this->firstGraspPoint.getVector3fMap(), this->secondGraspPoint.getVector3fMap());

with

float objWidth = pcl::geometry::distance(this->firstGraspPoint, this->secondGraspPoint);

as you mention above. However, I still get this error.


```
/usr/include/pcl-1.8/pcl/common/geometry.h: In instantiation of ‘float pcl::geometry::distance(const PointT&, const PointT&) [with PointT = Eigen::Matrix<float, 3, 1>]’:
/home/adelelakour/CLionProjects/GeoGrasp-master/geograsp/lib/geograsp/GeoGrasp.cpp:631:21:   required from here
/usr/include/pcl-1.8/pcl/common/geometry.h:62:33: error: ‘const class Eigen::Matrix<float, 3, 1>’ has no member named ‘getVector3fMap’
       Eigen::Vector3f diff = p1.getVector3fMap () - p2.getVector3fMap ();
                              ~~~^~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/common/geometry.h:62:56: error: ‘const class Eigen::Matrix<float, 3, 1>’ has no member named ‘getVector3fMap’
       Eigen::Vector3f diff = p1.getVector3fMap () - p2.getVector3fMap ();
                                                     ~~~^~~~~~~~~~~~~~
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /home/adelelakour/CLionProjects/GeoGrasp-master/geograsp/include/geograsp/GeoGrasp.h:23,
                 from /home/adelelakour/CLionProjects/GeoGrasp-master/geograsp/lib/geograsp/GeoGrasp.cpp:1:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
CMakeFiles/GeoGrasp.dir/build.make:75: recipe for target 'CMakeFiles/GeoGrasp.dir/lib/geograsp/GeoGrasp.cpp.o' failed
make[2]: *** [CMakeFiles/GeoGrasp.dir/lib/geograsp/GeoGrasp.cpp.o] Error 1
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/GeoGrasp.dir/all' failed
make[1]: *** [CMakeFiles/GeoGrasp.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

```

I tried to install PCL 1.7 along side PCL 1.8 (already installed on my ubuntu 18.04), but I can't access the old version of eigen lib (their site is down) 

Any suggestion? 

Regards
